// <auto-generated />
using Logistics.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Logistics.Migrations
{
    [DbContext(typeof(LogisticsDbContext))]
    [Migration("20221120163818_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.10");

            modelBuilder.Entity("Logistics.Domain.Subjects.Subject", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Subjects", (string)null);
                });

            modelBuilder.Entity("Logistics.Domain.Subjects.Subject", b =>
                {
                    b.OwnsOne("Logistics.Domain.Subjects.SubjectCode", "Code", b1 =>
                        {
                            b1.Property<string>("SubjectId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Code")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("SubjectId");

                            b1.ToTable("Subjects");

                            b1.WithOwner()
                                .HasForeignKey("SubjectId");
                        });

                    b.OwnsOne("Logistics.Domain.Subjects.SubjectDescription", "Description", b1 =>
                        {
                            b1.Property<string>("SubjectId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Descripion")
                                .HasColumnType("TEXT");

                            b1.HasKey("SubjectId");

                            b1.ToTable("Subjects");

                            b1.WithOwner()
                                .HasForeignKey("SubjectId");
                        });

                    b.OwnsOne("Logistics.Domain.Subjects.SubjectName", "Name", b1 =>
                        {
                            b1.Property<string>("SubjectId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("SubjectId");

                            b1.ToTable("Subjects");

                            b1.WithOwner()
                                .HasForeignKey("SubjectId");
                        });

                    b.Navigation("Code");

                    b.Navigation("Description");

                    b.Navigation("Name");
                });
#pragma warning restore 612, 618
        }
    }
}
