@startuml

title "Study Center - Domain Model"

package Test{
    class Test <Root>

    class Answer<VO>

    Test "1" -- "*" Answer
}

package Subject{
    class Subject <Root>

    class Code <VO>
    class SubjectName <VO>
    class SubjectDescription <VO>

    Subject "1" -- "1" Code
    Subject "1" -- "1" SubjectName
    Subject "1" -- "1" SubjectDescription

    class Category <Entity>
    class CategoryName <VO>
    class CategoryDescription <VO>

    Category "1" -- "1" CategoryName
    Category "1" -- "1" CategoryDescription

    class Question <Entoty>

    class Number <VO> 
    class Type <VO>
    class Text <VO>

    Question "1" -- "1" Number
    Question "1" -- "1" Text
    Question "1" -- "1" Type
}

'Relationships

Subject "1" -r- "*" Category: > addresses

Category "1" -r- "*" Question: > contains

Test "*" -- "1" Subject: < creates

@enduml